version: '3.8'

services:
  elixir_svc:
    build:
      context: .
      dockerfile: Dockerfile.base_elixir_service
    ports:
      - "4000:4000"
    depends_on:
      - cassandra
      - postgres
      - redis
      - rust_svc

  rust_svc:
    build:
      context: .
      dockerfile: Dockerfile.base_rust_service
    ports:
      - "5000:5000"
    depends_on:
      - redis

  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: dc_clone
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  cassandra_data:
  postgres_data:
  redis_data: